### ISSUE TITLE
Support for complex devices (DS28E17/18)

### ISSUE THREAD

**Issue by rgillan** [owfs/owfs-doc#1]
Hello,
Been using owfs and it makes dealing with simple things like switches and basic sensors rather trivial.  We have attached a DS28E17 1-wire slave to I2C master device and it gets discovered correctly (family code 19), and we were wondering if there was anyone working on functional support for this (and the newer DS28E18 cousin) device type?
Thanks

**Comment by ianka** [comment]
The DS28E17 isn't supported by OWFS as its functionality is hardly useful in this context. It's transparent to onewire, and the plethora of I²C devices out there which you may connect to it is beyond the scope of OWFS.

Instead, I wrote a w1_ds28e17 kernel driver a few years ago. It's part of the official Linux kernel since 4.15rc1, so all you have to do is to configure your installation for it. You can also use OWFS with the same onewire hostadapter in parallel if you configure it with the w1 option. That one advises OWFS to use the kernel driver for hardware access. (Caveat: as there are no kernel drivers for the RS232 onewire host adapters, you cannot use those with the DS28E17.)

I read up a bit about the DS28E18. Most likely its I²C mode could be supported similarly to that of the DS28E17 but it's more tricky to use as it has a more general approach. I'm not sure about the SPI mode, as it had to be compatible to the way the kernel manages SPI, and that's very basic only yet IIRC.

**Comment by rgillan** [comment]
Thanks so much for the prompt response and understand.  I will checkout the kernel module, thanks again
